#!/bin/csh -f
#
# @(#)$Header$
#
## HEADER ########################################################
#
# This script sets up the environment variables needed for compiling
# and linking to the edss_tools library.
#
##################################################################

if ( $?EDSS_SUBSYS ) then

   #  Set directories
   source $EDSS_SUBSYS/edss_tools/setup/set_dirs.scr

   #  Get system-specific flags
   source $EDSS_SUBSYS/edss_tools/setup/sysflags

else 
   echo "ERROR: EDSS Tools \"Setup\" script requires setting of the EDSS_SUBSYS"
   echo "       environment variable prior to using it."
   set status = 1

endif

exit( $status )
