#!/bin/csh -f
#
# @(#)$Header$
#
## HEADER ########################################################
#
# This script sets up the environment variables needed for using running
# the Txt2asci converter for Innogy.
#
##################################################################

if ( $?EDSS_SUBSYS ) then
else
   echo "ERROR: EDSS Tools \"Setup\" script requires setting of the EDSS_SUBSYS"
   echo "       environment variable prior to using it."
endif

#  Set directories
   source set_dirs.scr

#  Get system-specific flags
   source sysflags

