#!/bin/csh -f

# @(#)$Header$ 

#  Determine operating system for compiling SMOKE
source $EDSS_ROOT/scripts/platform

if ( $status != 0 ) then
    exit( $status )
endif

source $EDSS_SUBSYS/filesetapi/Setup

# Make directories for library, object files, and executables
setenv    TOOLS_BIN "$TOOLS_ROOT/$EDSS_EXE"
if( ! -e $TOOLS_BIN ) mkdir -p $TOOLS_BIN
if( ! -e $ETDSRC/$EDSS_EXE ) mkdir -p $ETDSRC/$EDSS_EXE

switch ( $EDSS_EXE )
  case IRIXn32f90:
  case IRIX6f90:
  case IRIXn64f90:
    setenv FC    f90
    setenv FFLAGS   "$FFLAGS -I${ETINC} -I${IOINC} -I${ETDSRC}/${EDSS_EXE} -I${FS_ROOT}"
    setenv DBGFLAGS "$DBGFLAGS -I${ETINC} -I${IOINC} -I${ETDSRC}/${EDSS_EXE}  -I${FS_ROOT}"
    setenv LDIRS    "-L${TOOLS_BIN}"
    breaksw
  case SunOS5f90:
#   NOTE: -Bstatic caused problems with ENVYN (perhaps because not
#         using I/O API compiled with f90 ?)
    setenv FC    f90
    setenv FFLAGS   "$FFLAGS -I${ETINC} -I${IOINC} -M${ETDSRC}/${EDSS_EXE} -I${FS_ROOT}"
    setenv DBGFLAGS "$DBGFLAGS -I${ETINC} -I${IOINC} -M${ETDSRC}/${EDSS_EXE} -I${FS_ROOT}"
    setenv LDIRS    "-L${TOOLS_BIN}"
    breaksw
case HP_UX11f90:
    setenv FC  f90
    setenv FFLAGS   "$FFLAGS  -I${ETINC} -I${IOINC} -I${ETDSRC}/${EDSS_EXE} -I${FS_ROOT}"
    setenv DBGFLAGS "$DBGFLAGS -I${ETINC} -I${IOINC} -I${ETDSRC}/${EDSS_EXE} -I${FS_ROOT}"
    setenv LDIRS    "+U77 -Wl,-L,${TOOLS_BIN}"
    breaksw
case AIX4n64f90:
case AIX4f90:
    setenv FC  xlf
    setenv FFLAGS   "$FFLAGS  -I${ETINC} -I${IOINC} -I${ETDSRC}/${EDSS_EXE} -I${FS_ROOT}"
    setenv DBGFLAGS "$DBGFLAGS -I${ETINC} -I${IOINC} -I${ETDSRC}/${EDSS_EXE} -I${FS_ROOT}"
    setenv LDIRS    "-L${TOOLS_BIN} -lxlsmp"
    breaksw
case Linux2_alpha:
    setenv FC  fort
    setenv FFLAGS   "$FFLAGS  -I${ETINC} -I${IOINC} -I${ETDSRC}/${EDSS_EXE} -I${FS_ROOT}"
    setenv DBGFLAGS "$DBGFLAGS -I${ETINC} -I${IOINC} -I${ETDSRC}/${EDSS_EXE} -I${FS_ROOT}"
    setenv LDIRS    "-L${TOOLS_BIN}"
    breaksw
case Linux2_x86ifc:
    setenv FC  ifc
    setenv FFLAGS   "$FFLAGS -cl,${ETDSRC}/${EDSS_EXE}/edss.pcl -I${ETINC} -I${IOINC} -I${ETDSRC}/${EDSS_EXE} -I${FS_ROOT}"
    setenv DBGFLAGS "$DBGFLAGS -I${ETINC} -I${IOINC} -I${ETDSRC}/${EDSS_EXE} -I${FS_ROOT}"
    setenv LDIRS    "-L${TOOLS_BIN}"
    breaksw
case  Linux2_x86pg:
    setenv FC  pgf90
    setenv FFLAGS   "$FFLAGS -I${ETINC} -I${IOINC} -I${ETDSRC}/${EDSS_EXE} -I${FS_ROOT}"
    setenv DBGFLAGS "$DBGFLAGS -I${ETINC} -I${IOINC} -I${ETDSRC}/${EDSS_EXE} -I${FS_ROOT}"
    setenv LDIRS    "-L${TOOLS_BIN}"
    breaksw
default:
    echo "Do not know about executable format "$EDSS_EXE
    exit( 2 )
endsw

echo " "
echo "Host name:             "`hostname`
echo "Platform type:         $EDSS_EXE"
echo "Executable directory:  $TOOLS_BIN"
echo " "

unalias mv
